/**
 * Represents an user and his location.
 * As of right now, there are no user details
 * so the location id is the user identifier
 * generated by their device
 */

export type Location = {
  _id: string;
  updatedAt: number;
  loc: {
    type: 'Point';
    coordinates: [number, number];
  };
};
