version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: heroes
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  geo-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geo-service
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/app/src

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
